#!/usr/bin/env python3
"""Text hygiene checks for the BaToHub repository.

The checker reports emoji, wording that must not appear in the project, contact
handles outside documentation, references to a removed licensing layer, and
unsafe shell execution patterns. It exits non-zero when anything is found.
"""

import os
import re
import sys

DOC_SUFFIXES = (".md",)
SOURCE_SUFFIXES = (".sh", ".json", ".html", ".conf", ".yml", ".yaml")
CONTACT = "@DatPHP"
FORBIDDEN_IDENTIFIERS = ("@BaTo_Help", "@BaToHub", "t.me/", "telegram")

# Files that legitimately contain the patterns they look for.
SKIP_NAMES = (
    os.path.join("scripts", "checks_text.py"),
    os.path.join("scripts", "checks.sh"),
    # The GNU GPL text is copied verbatim and must never be reworded.
    "LICENSE",
)

SKIP_DIRS = {".git", "node_modules", "__pycache__", "dist", "build", ".github"}

AI_PATTERNS = (
    r"\bAI\b",
    r"\bA\.I\.",
    r"artificial intelligence",
    r"generated by",
    r"co-authored-by",
    r"assisted by",
    r"powered by ai",
    r"chatgpt",
    r"openai",
    r"copilot",
    r"anthropic",
)

MARKETING_PATTERNS = (
    r"revolutionary",
    r"next-gen",
    r"next generation",
    r"blazing fast",
    r"seamless",
    r"empower",
    r"all-in-one",
    r"swiss army knife",
    r"game[- ]changing",
    r"cutting[- ]edge",
    r"state of the art",
    r"made with",
    r"coming soon",
    r"best[- ]in[- ]class",
)

UNSAFE_PATTERNS = (
    r"\| bash",
    r"\|\s*bash\b",
    r"eval\s+\"\$",
    r"eval\s+\$\{",
    r"curl[^\n]*-s[^\n]*\|\s*sh",
)

PLACEHOLDER_MARKERS = (
    r"\bTODO\b",
    r"\bFIXME\b",
    r"\bPLACEHOLDER\b",
    r"\blorem ipsum\b",
    r"\bnot implemented yet\b",
)

EMOJI = re.compile(
    "["
    "\U0001f000-\U0001faff"
    "\u2190-\u21ff"
    "\u2500-\u257f"
    "\u2580-\u259f"
    "\u2600-\u27bf"
    "\u2b00-\u2bff"
    "\ufe0f"
    "]"
)


def iter_files(root):
    for base, dirs, names in os.walk(root):
        dirs[:] = [name for name in dirs if name not in SKIP_DIRS]
        for name in names:
            yield os.path.join(base, name)


def read_text(path):
    try:
        with open(path, encoding="utf-8") as handle:
            return handle.read()
    except (OSError, UnicodeDecodeError):
        return None


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    problems = []

    for path in sorted(iter_files(root)):
        normalized = os.path.normpath(path)
        if any(normalized.endswith(os.path.normpath(name)) for name in SKIP_NAMES):
            continue
        text = read_text(path)
        if text is None:
            continue
        is_doc = path.endswith(DOC_SUFFIXES)
        is_source = path.endswith(SOURCE_SUFFIXES)

        if EMOJI.search(text):
            problems.append(f"emoji found in {path}")

        for pattern in AI_PATTERNS:
            if re.search(pattern, text, re.IGNORECASE):
                problems.append(f"possible AI related wording ({pattern}) in {path}")

        for pattern in MARKETING_PATTERNS:
            if re.search(pattern, text, re.IGNORECASE):
                problems.append(f"marketing wording ({pattern}) in {path}")

        if not is_doc and CONTACT in text:
            problems.append(f"contact handle used outside documentation: {path}")

        for identifier in FORBIDDEN_IDENTIFIERS:
            if identifier.lower() in text.lower():
                problems.append(f"forbidden identifier {identifier} in {path}")

        if is_source:
            for token in ("license_check", "validate_license", "license_server", "OpenLicense", "openlicense"):
                if token in text:
                    problems.append(f"licensing layer reference ({token}) in {path}")
            for pattern in UNSAFE_PATTERNS:
                if re.search(pattern, text):
                    problems.append(f"unsafe execution pattern ({pattern}) in {path}")
            for marker in PLACEHOLDER_MARKERS:
                if re.search(marker, text, re.IGNORECASE):
                    problems.append(f"placeholder marker ({marker}) in {path}")

    if problems:
        for item in sorted(set(problems)):
            print(f"FAIL [source hygiene] {item}", file=sys.stderr)
        return 1

    print("ok   text hygiene: no emoji, no forbidden wording, no licensing layer, no placeholders")
    return 0


if __name__ == "__main__":
    sys.exit(main())
