#!/usr/bin/env python3
"""Text hygiene checks for the BaToHub repository.

The checker reports emoji, wording that must not appear in the project, contact
handles outside documentation, references to a removed licensing layer, unsafe
shell execution patterns, downloads that do not follow redirects, and
placeholder markers. It exits non-zero when anything is found.

The contact handle is never written in this file: the rule is expressed
structurally. Exactly one handle may exist in the whole tree, it may only appear
in the documentation files listed below, and it must appear in every one of
them. A second handle, wherever it is, is reported.
"""

import os
import re
import sys

SOURCE_SUFFIXES = (".sh", ".json", ".html", ".conf", ".yml", ".yaml")

# Documentation files that may carry the project contact handle.
CONTACT_DOC_FILES = (
    "README.md",
    "README.fa.md",
    "DOCS.md",
    "DOCS.fa.md",
    "SECURITY.md",
)

# A handle is an at sign followed by a name at a word boundary, so an email
# address (name@host) and a GitHub action reference (actions/checkout@v4) are
# not handles. The JSON body builders use an at sign followed by a value type
# and a colon (@int:5, @json:{...}), so a following colon is not a handle.
HANDLE_PATTERN = re.compile(r"(?<![A-Za-z0-9._%+-])@[A-Za-z_][A-Za-z0-9_]{2,}(?![A-Za-z0-9_:])")

# CSS at-rules look like handles and are not contact information.
CSS_AT_RULES = frozenset({
    "media",
    "import",
    "supports",
    "keyframes",
    "font-face",
    "charset",
    "namespace",
    "page",
    "layer",
    "property",
    "container",
    "scope",
})

# Profile links to messaging and social platforms. An identifier is a profile
# link, not a platform name: the Telegram management bot is part of the product,
# so the name of the platform appears in the code and in the documentation.
FORBIDDEN_IDENTIFIERS = (
    "t.me/",
    "telegram.me/",
    "tg://",
    "wa.me/",
    "discord.gg/",
    "instagram.com/",
    "facebook.com/",
    "twitter.com/",
    "x.com/",
    "tiktok.com/",
    "youtube.com/@",
    "linkedin.com/in/",
)

# Files that legitimately contain the patterns they look for.
SKIP_NAMES = (
    os.path.join("scripts", "checks_text.py"),
    os.path.join("scripts", "checks.sh"),
    # The GNU GPL text is copied verbatim and must never be reworded.
    "LICENSE",
)

SKIP_DIRS = {".git", "node_modules", "__pycache__", "dist", "build"}

AI_PATTERNS = (
    r"\bAI\b",
    r"\bA\.I\.",
    r"artificial intelligence",
    r"generated by",
    r"generated with",
    r"co-authored",
    r"assisted by",
    r"ai-assisted",
    r"ai generated",
    r"ai-generated",
    r"powered by ai",
    r"auto-generated",
    r"automatically generated",
    r"built with ai",
    r"made with ai",
    r"chatgpt",
    r"openai",
    r"copilot",
    r"anthropic",
    r"claude",
    r"gemini",
    r"grok",
    r"deepseek",
    r"windsurf",
    r"\bllm\b",
    r"codebuff",
    # Cursor is a CSS property name as well as a product name, so a following
    # colon ("cursor: pointer") is not a match.
    r"cursor(?!\s*:)",
)

MARKETING_PATTERNS = (
    r"revolutionary",
    r"next[- ]gen",
    r"next generation",
    r"next[- ]level",
    r"blazing fast",
    r"seamless",
    r"empower",
    r"all-in-one",
    r"swiss army knife",
    r"game[- ]chang",
    r"cutting[- ]edge",
    r"state[- ]of[- ]the[- ]art",
    r"made with",
    r"coming soon",
    r"best[- ]in[- ]class",
    # Word boundaries keep the short entries from matching ordinary words:
    # "just" must not match "adjust" or "justify".
    r"(?<![a-z])just(?![a-z])",
    r"(?<![a-z])simply(?![a-z])",
    r"(?<![a-z])powerful(?![a-z])",
    r"(?<![a-z])robust(?![a-z])",
    r"(?<![a-z])elegant(?![a-z])",
    r"(?<![a-z])effortless(?![a-z])",
    r"(?<![a-z])unleash(?![a-z])",
    r"(?<![a-z])supercharge(?![a-z])",
    r"(?<![a-z])industry[- ]leading(?![a-z])",
    r"(?<![a-z])world[- ]class(?![a-z])",
    r"(?<![a-z])turnkey(?![a-z])",
    r"(?<![a-z])flawless(?![a-z])",
    r"(?<![a-z])future[- ]proof(?![a-z])",
    r"(?<![a-z])battle[- ]tested(?![a-z])",
    r"(?<![a-z])one[- ]stop(?![a-z])",
)

UNSAFE_PATTERNS = (
    r"\| bash",
    r"\|\s*bash\b",
    r"eval\s+\"\$",
    r"eval\s+\$\{",
    r"curl[^\n]*-s[^\n]*\|\s*sh",
)

PLACEHOLDER_MARKERS = (
    r"\bTODO\b",
    r"\bFIXME\b",
    r"\bPLACEHOLDER\b",
    r"\blorem ipsum\b",
    r"\bnot implemented yet\b",
)

# Unicode emoji: the emoji blocks, the symbol and dingbat ranges, the arrows and
# geometric shapes that are used as pictographs, and the variation selector.
# The copyright, registered and trademark signs are deliberately not included:
# a copyright notice may legitimately use them.
EMOJI = re.compile(
    "["
    "\U0001f000-\U0001faff"
    "\U0001f1e6-\U0001f1ff"
    "\U0000203c"
    "\U00002049"
    "\U000020e3"
    "\U00002139"
    "\U00002190-\U000021ff"
    "\U0000231a-\U0000231b"
    "\U00002328"
    "\U000023cf"
    "\U000023e9-\U000023f3"
    "\U000023f8-\U000023fa"
    "\U000024c2"
    "\U00002500-\U0000257f"
    "\U00002580-\U0000259f"
    "\U000025aa-\U000025ab"
    "\U000025b6"
    "\U000025c0"
    "\U000025fb-\U000025fe"
    "\U00002600-\U000027bf"
    "\U00002934-\U00002935"
    "\U00002b00-\U00002bff"
    "\U00003030"
    "\U0000303d"
    "\U00003297"
    "\U00003299"
    "\U0001f004"
    "\U0001f0cf"
    "\U0000fe0f"
    "]"
)


def logical_commands(text):
    """Yields one string per shell command, joining backslash continuations."""
    current = ""
    for line in text.splitlines():
        stripped = line.rstrip()
        if stripped.endswith("\\"):
            current += stripped[:-1] + " "
            continue
        current += stripped
        yield current
        current = ""
    if current:
        yield current


def download_redirect_problems(text):
    """curl commands that write to a file must follow redirects.

    A release asset URL answers with a redirect to the object store. Without
    --location curl stores the empty redirect body and still exits successfully,
    so the download is reported as complete while nothing was fetched. Every
    download that writes to a file is therefore required to follow redirects.
    """
    problems = []
    for command in logical_commands(text):
        if not re.search(r"\bcurl\b", command):
            continue
        if not re.search(r"(^|\s)(-o|--output)(\s|=)", command):
            continue
        # --location, or L inside a combined short option such as -fsSL.
        if re.search(r"(^|\s)(--location|-[A-Za-z]*L[A-Za-z]*)(\s|$)", command):
            continue
        problems.append(" ".join(command.split())[:120])
    return problems


def iter_files(root):
    for base, dirs, names in os.walk(root):
        dirs[:] = [name for name in dirs if name not in SKIP_DIRS]
        for name in names:
            yield os.path.join(base, name)


def read_text(path):
    try:
        with open(path, encoding="utf-8") as handle:
            return handle.read()
    except (OSError, UnicodeDecodeError):
        return None


def relative(path, root):
    """Path of a file relative to the scanned root, with forward slashes."""
    return os.path.relpath(path, root).replace(os.sep, "/")


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    problems = []
    handles = {}

    for path in sorted(iter_files(root)):
        normalized = os.path.normpath(path)
        if any(normalized.endswith(os.path.normpath(name)) for name in SKIP_NAMES):
            continue
        text = read_text(path)
        if text is None:
            continue
        is_source = path.endswith(SOURCE_SUFFIXES)
        name = relative(path, root)

        if EMOJI.search(text):
            problems.append(f"emoji found in {path}")

        for pattern in AI_PATTERNS:
            if re.search(pattern, text, re.IGNORECASE):
                problems.append(f"possible AI related wording ({pattern}) in {path}")

        for pattern in MARKETING_PATTERNS:
            if re.search(pattern, text, re.IGNORECASE):
                problems.append(f"marketing wording ({pattern}) in {path}")

        for match in HANDLE_PATTERN.finditer(text):
            handle = match.group(0)
            if handle[1:].lower() in CSS_AT_RULES:
                continue
            handles.setdefault(handle, set()).add(name)
            if name not in CONTACT_DOC_FILES:
                problems.append(f"contact handle {handle} used outside documentation: {path}")

        for identifier in FORBIDDEN_IDENTIFIERS:
            if identifier.lower() in text.lower():
                problems.append(f"forbidden identifier {identifier} in {path}")

        if is_source:
            for token in ("license_check", "validate_license", "license_server", "OpenLicense", "openlicense"):
                if token in text:
                    problems.append(f"licensing layer reference ({token}) in {path}")
            for pattern in UNSAFE_PATTERNS:
                if re.search(pattern, text):
                    problems.append(f"unsafe execution pattern ({pattern}) in {path}")
            for marker in PLACEHOLDER_MARKERS:
                if re.search(marker, text, re.IGNORECASE):
                    problems.append(f"placeholder marker ({marker}) in {path}")
            for command in download_redirect_problems(text):
                problems.append(f"download writes to a file without following redirects in {path}: {command}")

    # One contact handle for the whole project, only in the documentation, in
    # every documentation file.
    if len(handles) != 1:
        found = ", ".join(sorted(handles)) if handles else "none"
        problems.append(f"the project must use exactly one contact handle; found {len(handles)}: {found}")
    else:
        handle, files = next(iter(handles.items()))
        missing = [name for name in CONTACT_DOC_FILES if name not in files]
        if missing:
            problems.append(f"the contact handle {handle} is missing from: {', '.join(sorted(missing))}")

    if problems:
        for item in sorted(set(problems)):
            print(f"FAIL [source hygiene] {item}", file=sys.stderr)
        return 1

    print("ok   text hygiene: no emoji, no forbidden wording, one contact handle in the documentation only,")
    print("ok   no licensing layer, no placeholders, every download follows redirects")
    return 0


if __name__ == "__main__":
    sys.exit(main())
